### ISSUE TITLE
Build OPM1.180104.234 is not yet supported

### ISSUE THREAD

**Issue by rbabchis** [thehappydinoa/root-PH1#6]
Essential's latest release for the PH-1 is build: OPM1.180104.234

https://github.com/EssentialOpenSource/linux/releases/tag/OPM1.180104.234

Please add support for this release. Thanks!

**Comment by thehappydinoa** [comment]
Fixed in 64ddad5c443a3c0d71261ae7063c3321f0f8b4e8
